AllCops:
  Exclude:
    - "README.md"
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true
UselessAssignment: 
  Enabled: false
Layout/LineLength:
  Max: 125
Metrics/MethodLength:
  Max: 50
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30
Metrics/ModuleLength:
  Max: 500
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 20
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/CaseEquality:
  Enabled: false
#Style/GuardClause:
  #Enabled: false
#Style/MultipleComparison:
  #Enabled: false
#Lint/UselessAssignment:
  #Enabled: false
Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/NegatedUnless:
  Enabled: false
Style/For:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false


